port: "8080"
db_host: "localhost"
db_port: "3306"
db_username: "main"
db_password: "main"
db_name: "main"

# db_host: "localhost"
# db_port: "3306"
# db_username: "pm_user"
# db_password: "123ZXCzxc"
# db_name: "pm"